language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.9.5
install:
  - pip install django==$DJANGO --quiet
  - pip install -r requirements.txt
script:
  – python manage.py test
