language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.9.2
install:
  - pip install django==$DJANGO --quiet
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - python manage.py test
  - coverage run --source=loremimg manage.py test
after_success: coveralls
