# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(choices=[('LANDSCAPES', 'Landscapes'), ('ARCHITECTURE', 'Architecture'), ('PEOPLE', 'People'), ('ANIMALS', 'Animals'), ('VARIOUS', 'Various')], default='VARIOUS', max_length=20)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
